name: Build LaTeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: PhD_thesis__Edouard_Leurent.tex
          args: -pdf -file-line-error -interaction=nonstopmode -shell-escape
          extra_system_packages: "py-pygments"
        continue-on-error: true
      - name: Upload log as an artifact
        uses: actions/upload-artifact@v2
        with:
          path: PhD_thesis__Edouard_Leurent.log
      - name: Upload pdf as an artifact
        uses: actions/upload-artifact@v2
        with:
          path: PhD_thesis__Edouard_Leurent.pdf
